add_newline = false
prompt_order = [
  "username",
  "custom.tmux",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "cmd_duration",
  "line_break",
  "character",
]

[line_break]
disabled = false

[directory]
truncation_length = 1
truncate_to_repo = true

[username]
show_always = true

[nodejs]
disabled = true

[python]
disabled = true

[custom.tmux]
# command = "echo -e '\b<t>'"
command = "echo tmux"
when = """[ -n "$TMUX" ]"""
description = "Show if running in tmux"
# prefix = ""
style = "bold bright-green"
