add_newline = false
prompt_order = [
  "username",
  "custom.tmux",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "python",
  "cmd_duration",
  "line_break",
  "character",
]

[line_break]
disabled = false

[directory]
truncation_length = 1
truncate_to_repo = true

[username]
show_always = true

[nodejs]
disabled = true

[python]
symbol = ""
pyenv_version_name = false
python_binary = "python3"

[custom.tmux]
command = "echo tmux"
when = """[ -n "$TMUX" ]"""
description = "Show if running in tmux"
style = "bold bright-green"
