add_newline = false

format = """$username$host$custom$directory$git_branch$git_commit$git_state$git_status$cmd_duration\n$character"""

[directory]
truncation_length = 1
truncate_to_repo = true
format = " in [$path]($style) [$read_only]($read_only_style)"

[username]
show_always = true
format = "[$user]($style)"

[hostname]
ssh_only = false

[custom.tmux]
command = "tmux display-message -p '#S'"
when = "[ -n \"$TMUX\" ]"
description = "Show if running in tmux"
style = "bold bright-green"
format = ':[tm\(]($style)[$output](white)[\)]($style)'
